### PR TITLE
feat: Content in Vue + mini integration

### PR DESCRIPTION
**Pull request by BRAVO68WEB**

### CODE REVIEW

**Comment by BRAVO68WEB** [comment]
@RamanSharma100 Check this content rendering in Vue

**Comment by RamanSharma100** [comment]
Yes I know about this but we don't need this for now as we are using json

**Comment by BRAVO68WEB** [comment]
I used json only check in content folder

**Comment by RamanSharma100** [comment]
hmm... its looking good, deploy it and lets see

**Review by RamanSharma100 — APPROVED** [review]

**Pull request merged**
